### PR TITLE
toast notification functionality for Read Docs and Get Started in Banner component.

### PR DESCRIPTION
**Pull request by mayankmehta19032003**
This feature utilizes React Toastify to display a brief notification when the "Read Docs" button is clicked, informing users that the documentation is currently under development.

Here is the screenshoot : 
Screenshot 2024-10-13 154058

Steps to Remove Notification Functionality:

1. Remove the import statements for ToastContainer and toast and its Css.
2. Delete the line.
3. Remove the div wrapping the ReadDocsButton that contains the onClick handler.

### CODE REVIEW

**Comment by mayankmehta19032003** [comment]
fixes - #6

**Comment by saurabhmehta1601** [comment]
@mayankmehta19032003 can you display the same popup/alert when user clicks Get Started ?

**Comment by mayankmehta19032003** [comment]
Add notification on Get started also now its working on both Read Docs and  Get started .

**Comment by saurabhmehta1601** [comment]
@mayankmehta19032003 Thanks ! Everything looks good to me 👍

**Pull request merged**
